# Generated by Django 4.0.4 on 2024-11-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-datetime'], 'verbose_name': 'Archive', 'verbose_name_plural': 'Archives'},
        ),
    ]
